### PR TITLE
✨ Add end to end testing capabilities

### PR DESCRIPTION
**Pull request by benoitgrelard**
Ok, so I've got it to the point you were at yesterday so now the build passes.
A few things before we merge though:

- Although this passes on the CI env, for me the newly added `which google-chrome` check fails on my local machine, I'd like to have something that passes both locally and on CI.
- We're installing chrome driver using the npm wrapper. This is because I didn't know any other way, but we should be able to install it the way you installed chrome maybe?
- Although it ends with a status 0 and a success on Travis, I am not happy with the weird output it produces when killing webpack-dev-server, looks like an error...

Anything else you can see?

### CODE REVIEW

**Comment by nickebbutt** [comment]
The following fixes are on e2e script on my fork / master and pass the travis build from the fork !- please take them from there!
https://travis-ci.org/nickebbutt/Chorus-JS/builds/190603015
https://github.com/nickebbutt/Chorus-JS/blob/master/e2e

1. I have changed the script to check for either google-chrome or chrome executable
2. It might work to install it the same way as chrome - I'm a bit surprised npm installs the wrapper without chrome underneath - surely everyone else doing that would have had the same problem we're having. I don't think this one is all that important so long as travis is working for us, I'll leave it for now 
3. This is now fixed by capturing the PID from the npm start command, rather than using lsof which was probably only terminating a child process of the parent npm start

**Comment by benoitgrelard** [comment]
Hey @nickebbutt, thanks for the changes.

On my machine the check for Chrome still doesn’t work.
`which chrome` and `which google-chrome` both don’t return anything.
For information this it my path for Chrome on mac: `/Applications/Google Chrome.app`

What do you think?

**Comment by benoitgrelard** [comment]
@nickebbutt, ok so I've fixed the issue that the chrome detection was failing locally by only checking for it if we're on the CI environment (see here: https://github.com/Chorus-bdd/chorus-js/pull/5/files#diff-0d1f3b0802c73b1e989b36551deb0193R83).

However, I now have another issue (not related though) due to the change you made in the way we kill the background task. It doesn't seem to be killed properly and that means I can't run a second test straight after because it says that port 9000 is still in use.

Here are some output for you:

From our script:
```
...
webpack-dev-server pid is 27057
...
Killing webpack-dev-server using pid 27057
Killed webpack-dev-server
```

During our script run, `ps -edf | grep webpack` outputs this:

```
502 27070 27057   0  2:11PM ttys001    0:00.83 node /Users/benoit/Projects/artisologic/chorus-js/node_modules/.bin/webpack-dev-server --progress --colors --inline --hot --quiet
502 27072   703   0  2:11PM ttys002    0:00.00 grep webpack
```

After our script is finished, `ps -edf | grep webpack` outputs this:

```
502 27070     1   0  2:11PM ttys001    0:02.08 node /Users/benoit/Projects/artisologic/chorus-js/node_modules/.bin/webpack-dev-server --progress --colors --inline --hot --quiet
502 27157   703   0  2:11PM ttys002    0:00.00 grep webpack
```

This is something I noticed and struggled with also when I was trying to find my own solution to this.
The only way I can kill everything properly and have a clean output was to use the first number: `27070` so for example: `kill -9 27070`.

What do you think?

**Comment by benoitgrelard** [comment]
Ok! @nickebbutt ready to be merge I think!

**Review by nickebbutt — APPROVED** [review]
Great this is all working for me and travis looks good. Having these tests in place will really help us going forward

**Pull request merged**
